CREATE TABLE VENDING_MACHINE(
  VENDING_MACHINE_ID INT NOT NULL, 
  LOCATION VARCHAR(30), 
  AMOUNT_OF_ITEMS INT, 
  TOTAL_MONEY DOUBLE,
  PRIMARY KEY(VENDING_MACHINE_ID)
);

CREATE TABLE ITEM(
  ID VARCHAR(2) NOT NULL, 
  NAME VARCHAR(20), 
  PRODUCTION_COMPANY VARCHAR(30), 
  PRICE DOUBLE,
  QUANTITY INT NOT NULL,
  VENDING_MACHINE_ID INT NOT NULL,
  PRIMARY KEY(ID, VENDING_MACHINE_ID),
  FOREIGN KEY (VENDING_MACHINE_ID) REFERENCES VENDING_MACHINE(VENDING_MACHINE_ID)
);



INSERT INTO VENDING_MACHINE(
    VENDING_MACHINE_ID, LOCATION, AMOUNT_OF_ITEMS, TOTAL_MONEY
)
VALUES
    (1, '153 Main St.', 20, 50.00);

INSERT INTO VENDING_MACHINE(
    VENDING_MACHINE_ID, LOCATION, AMOUNT_OF_ITEMS, TOTAL_MONEY
)
VALUES
    (2, '5031 Audrey St.', 24, 123.43);



INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('A1', 'Ruffles Original', 'Frito-Lay', 1.29, 4, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('A2', 'Ritz', 'Ritz Crackers', 0.99, 6, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('A3', 'Doritos Cool Ranch', 'PepsiCo', 1.29, 5, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('A4', 'Doritos Nacho Cheese', 'PepsiCo', 1.29, 8, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('B1', 'Fritos', 'Frito-Lay', 1.29, 4, 1);

INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('B2', 'Popchips Sea Salt Potato', 'Popchips Inc.', 0.99, 9, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('B3', 'Cheetos', 'Frito-Lay', 1.29, 2, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('B4', 'SunChips Original', 'Frito-Lay', 1.09, 9, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('C1', 'SunChips French Onion', 'Frito-Lay', 1.09, 4, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('C2', 'Pringles Original', "Kellog's", 1.29, 4, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('C3', 'Pringles Sour Cream & Onion', "Kellog's", 1.29, 9, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('C4', 'Lays Classic', "PepsiCo", 1.29, 2, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('D1', 'Lays Barbeque', "PepsiCo", 1.29, 5, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('D2', 'Oreos', "Nabisco", 1.09, 6, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('D3', 'Popchips Sea Salt Potato', "Nabisco", 0.99, 7, 1);
  
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('D4', 'Lays Classic', "PepsiCo", 1.29, 9, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('E1', 'Lays Barbeque', "PepsiCo", 1.29, 6, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('E2', 'Gummy Bears', "Nairb Inc.", 0.99, 9, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('E3', 'Snickers', "Mars Inc.", 0.99, 6, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('E4', 'Twix', "Mars Inc.", 0.99, 5, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('F1', 'Hesheys Chocolate', "Hershey Co.", 0.99, 7, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('F2', 'Reeses Peanut Butter Cups', "Hershey Co.", 0.99, 4, 1);
  
INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('F3', 'Green Tea KitKat', "Nestle", 0.99, 1, 1);

INSERT INTO ITEM(
  ID, NAME, PRODUCTION_COMPANY, PRICE, QUANTITY, VENDING_MACHINE_ID
) 
VALUES 
  ('F4', 'KitKat', "Nestle", 3.99, 3, 1);